In [2]:
class Cars():
    def __init__(self, name, engine):
        self.name = name
        self.engine = engine
    def move(self):
        print("Car is moving")
    def brake(self):
        print("Car is stopped")

Corolla = Cars("Toyota", "1300cc")



In [7]:
print(Corolla.name)
print(Corolla.engine)

Toyota
1300cc


In [8]:
Corolla.move()

Car is moving


In [9]:
Corolla.name = "Honda"

In [10]:
print(Corolla.name)

Honda


In [11]:
class Navi():
    def __init__(self, x, y):
        self.x = x
        self.y = y
    def newlocation(self, x1, y1):
        self.x = x1
        self.y = y1

dot = Navi(0,0)



In [18]:
import numpy as np
dot.newlocation(2,3)


In [13]:
dot.x

2

In [14]:
dot.y

3

In [17]:
a = [1, 2, 3, 4, 5]
print(type(a))

<class 'list'>


In [30]:
a = np.array([[10, 20, 30, 40, 50], 
              [60, 70, 80, 90, 100]])
type(a)

numpy.ndarray

In [20]:
a.dtype

dtype('int32')

In [22]:
a.ndim

1

In [23]:
a.shape

(5,)

In [24]:
a.size

5

In [29]:
b = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10]])
b.dtype
b.shape
b.ndim
b.size

10

In [31]:
a + b

array([[ 11,  22,  33,  44,  55],
       [ 66,  77,  88,  99, 110]])

In [32]:
a-b

array([[ 9, 18, 27, 36, 45],
       [54, 63, 72, 81, 90]])

In [33]:
a*2


array([[ 20,  40,  60,  80, 100],
       [120, 140, 160, 180, 200]])

In [40]:
a[0] = 10.2
a

array([[ 10,  10,  10,  10,  10],
       [ 60,  70,  80,  90, 100]])

In [48]:
c = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

In [49]:
c.ndim

2

In [76]:
c[0, 0] = 1
print(c[0,0])

1


In [93]:
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [94]:
print(c[[0,1,2],[3 ,2, 1]])

[ 4  7 10]


In [95]:
for x in c:
    for y in x:
        print(y)

1
2
3
4
5
6
7
8
9
10
11
12


In [96]:
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [97]:
print(c[1:, 0::3])

[[ 5  8]
 [ 9 12]]


In [117]:
z = np.arange(25).reshape(5,5)
print(z)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [113]:
x = np.ones((5,5), dtype=np.int8)

In [114]:
print(x)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [118]:
print(z[[0,1,2,3], [1,2,3,4]])

[ 1  7 13 19]


In [123]:
print(z[0::2, 0::2])

[[ 0  2  4]
 [10 12 14]
 [20 22 24]]


In [129]:
K=z%2==0
print(K)

[[ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]]


In [131]:
print(z[K])

[ 0  2  4  6  8 10 12 14 16 18 20 22 24]


In [135]:
np.savetxt('zmask.csv', z[K], delimiter=',')